# Generated by Django 4.2.6 on 2023-11-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travelapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=250)),
                ("imgs", models.ImageField(upload_to="pics")),
                ("descs", models.TextField()),
            ],
        ),
    ]
